dist: bionic
language: go
go:
  - 1.13.x
  - master
  - tip
os:
  - linux
  - osx
env: MOD=github.com/romnnn/testcontainers BINARY=testcontainers

jobs:
  allow_failures:
    - go: tip
  fast_finish: true
  
install: true
notifications:
  email: false
before_script:
  - pip install -U pip && pip install pre-commit invoke ruamel.yaml
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get github.com/mitchellh/gox
script:
  - invoke pre-commit
  - env GO111MODULE=on go build ${MOD}
  - env GO111MODULE=on go test -v -race -coverprofile=coverage.txt -coverpkg=all -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)